In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
tips_df = sns.load_dataset('tips')

In [3]:
tips_df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
tips_df.shape

(244, 7)

In [5]:
pd.get_dummies(tips_df) #One hot encoding for every column

total_bill   tip  size  sex_Male  sex_Female  smoker_Yes  smoker_No  \
0         16.99  1.01     2         0           1           0          1   
1         10.34  1.66     3         1           0           0          1   
2         21.01  3.50     3         1           0           0          1   
3         23.68  3.31     2         1           0           0          1   
4         24.59  3.61     4         0           1           0          1   
..          ...   ...   ...       ...         ...         ...        ...   
239       29.03  5.92     3         1           0           0          1   
240       27.18  2.00     2         0           1           1          0   
241       22.67  2.00     2         1           0           1          0   
242       17.82  1.75     2         1           0           0          1   
243       18.78  3.00     2         0           1           0          1   

     day_Thur  day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0           0        0        0        1           0            1  
1           0        0        0        1           0            1  
2           0        0        0        1           0            1  
3           0        0        0        1           0            1  
4           0        0        0        1           0            1  
..        ...      ...      ...      ...         ...          ...  
239         0        0        1        0           0            1  
240         0        0        1        0           0            1  
241         0        0        1        0           0            1  
242         0        0        1        0           0            1  
243         1        0        0        0           0            1  

[244 rows x 13 columns]

In [6]:
pd.get_dummies(tips_df,drop_first=True) #One hot encoding for every column

total_bill   tip  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  \
0         16.99  1.01     2           1          1        0        0        1   
1         10.34  1.66     3           0          1        0        0        1   
2         21.01  3.50     3           0          1        0        0        1   
3         23.68  3.31     2           0          1        0        0        1   
4         24.59  3.61     4           1          1        0        0        1   
..          ...   ...   ...         ...        ...      ...      ...      ...   
239       29.03  5.92     3           0          1        0        1        0   
240       27.18  2.00     2           1          0        0        1        0   
241       22.67  2.00     2           0          0        0        1        0   
242       17.82  1.75     2           0          1        0        1        0   
243       18.78  3.00     2           1          1        0        0        0   

     time_Dinner  
0              1  
1              1  
2              1  
3              1  
4              1  
..           ...  
239            1  
240            1  
241            1  
242            1  
243            1  

[244 rows x 9 columns]

In [7]:
# Using scikit learn
from sklearn.preprocessing import OneHotEncoder

In [8]:
onehotencoder = OneHotEncoder(sparse_output=False)

In [9]:
ohe_arr = onehotencoder.fit_transform(tips_df[['sex','smoker','day','time']])

In [10]:
ohe_arr #the array is ondehotencoded but the array have more than 4 columns and if we have to create dataframe than we need to get keys from pd.get_dummies

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [11]:
# ordinal variables ---> grade,condition,---> USE ORDINALENCODER
# nominal varible --> language,products,colors-->USE LABELENCODER (if data have too many different classes) --->USE ONEHOTENCODER(if column have few classes like male female) 

In [12]:
# Ordinal encoding ==>encode data according to level

In [13]:
# LabelEncoder
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder() # convert data into numbers according to alphabetical order
le.fit_transform(tips_df['day'])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [15]:
le.fit_transform(tips_df['time'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [16]:
# OrdinalEncoder manuaaly (better approach for many times)
order_label = {'Dinner':2,'Lunch':1} # first, define the order of diffrent classes
tips_df['time'].map(order_label) # then  just map the order on column

0      2
1      2
2      2
3      2
4      2
      ..
239    2
240    2
241    2
242    2
243    2
Name: time, Length: 244, dtype: category
Categories (2, int64): [1, 2]

In [17]:
# Scikit learn OrdinalEncoder ()
from sklearn.preprocessing import OrdinalEncoder
ordinalencoder = OrdinalEncoder()

In [18]:
# always keep in mind tnat use ordinalencoder only when the data is in a perticular order
#  I am just applying ordinalencoder for practice 
ordinalencoder.fit_transform(tips_df[['day','time']]) # 2D array required

array([[2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [19]:
# these are most common encoding techniques 
# there are many more encoding techniques which are useful for special cases

Kalu Ram Kharra --> Follow me for more data science related projects