In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
np.array([2,3,4,5])


array([2, 3, 4, 5])

In [4]:
np.array([[2,3,4,5,5],[3,2,1,4,5]])

array([[2, 3, 4, 5, 5],
       [3, 2, 1, 4, 5]])

In [5]:
np.array([[1,2,4,5,6],[1,23,3,4,5]])

array([[ 1,  2,  4,  5,  6],
       [ 1, 23,  3,  4,  5]])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
ful = np.full((2,4),5)
ful

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
for i in ful:
    for j in i:
        print(j)
    print(i)

5
5
5
5
[5 5 5 5]
5
5
5
5
[5 5 5 5]


In [11]:
ful[0][2] == 4

False

In [12]:
ful[0][2] = 6

In [13]:
ful

array([[5, 5, 6, 5],
       [5, 5, 5, 5]])

In [14]:
np.random.random([2,3])

array([[0.56728247, 0.32984257, 0.15742406],
       [0.90938819, 0.408559  , 0.73733073]])

In [15]:
np.random.random([4,5])

array([[0.85736323, 0.31873953, 0.10654466, 0.13852236, 0.59932756],
       [0.76770429, 0.9207845 , 0.89530802, 0.11969891, 0.35498239],
       [0.80557261, 0.65480107, 0.85095721, 0.53158615, 0.45919463],
       [0.38373596, 0.18485447, 0.28700949, 0.7686882 , 0.81677536]])

In [16]:
np.arange(10,25,5)

array([10, 15, 20])

In [17]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
np.empty((2,3))

array([[0.56728247, 0.32984257, 0.15742406],
       [0.90938819, 0.408559  , 0.73733073]])

In [19]:
arr = np.random.random((3,4))

In [20]:
arr.size

12

In [21]:
arr.shape

(3, 4)

In [22]:
len(arr),len(arr[2])

(3, 4)

In [23]:
arr.ndim

2

In [24]:
arr.dtype #print the type of array elements

dtype('float64')

In [25]:
arr.dtype.name

'float64'

In [26]:
# array mathematics
a = np.random.random((3,4)) # we can only use sum and subtraction,divide and multiply if both the arrays are have same dimension
b = np.random.random((3,4))

In [27]:
a-b,np.subtract(a,b)  #both are the same functionalities

(array([[ 0.28992799,  0.4902314 ,  0.17034559, -0.45326547],
        [ 0.45834972,  0.46964528,  0.37117078, -0.48702155],
        [-0.26418973,  0.42461386,  0.32678048,  0.1043759 ]]),
 array([[ 0.28992799,  0.4902314 ,  0.17034559, -0.45326547],
        [ 0.45834972,  0.46964528,  0.37117078, -0.48702155],
        [-0.26418973,  0.42461386,  0.32678048,  0.1043759 ]]))

In [28]:
a+b,np.add(a,b) #both are the same functionalities

(array([[0.64418942, 0.68226912, 1.27141956, 1.18974617],
        [0.82226361, 0.73268004, 0.63570966, 1.13990204],
        [0.75538516, 1.11207797, 1.26880835, 1.78562774]]),
 array([[0.64418942, 0.68226912, 1.27141956, 1.18974617],
        [0.82226361, 0.73268004, 0.63570966, 1.13990204],
        [0.75538516, 1.11207797, 1.26880835, 1.78562774]]))

In [29]:
a/b,np.divide(a,b)  #both are the same functionalities

(array([[2.63680248, 6.10557382, 1.30941717, 0.44825045],
        [3.51900099, 4.57097507, 3.80617177, 0.40129758],
        [0.48176494, 2.23530481, 1.69378091, 1.1241645 ]]),
 array([[2.63680248, 6.10557382, 1.30941717, 0.44825045],
        [3.51900099, 4.57097507, 3.80617177, 0.40129758],
        [0.48176494, 2.23530481, 1.69378091, 1.1241645 ]]))

In [30]:
a*b,np.multiply(a,b)  #both are the same functionalities

(array([[0.08273044, 0.05629108, 0.39687252, 0.30251159],
        [0.11650824, 0.07906334, 0.06658976, 0.26554667],
        [0.12520263, 0.26410512, 0.37577229, 0.79439303]]),
 array([[0.08273044, 0.05629108, 0.39687252, 0.30251159],
        [0.11650824, 0.07906334, 0.06658976, 0.26554667],
        [0.12520263, 0.26410512, 0.37577229, 0.79439303]]))

In [31]:
np.exp(a)

array([[1.59529505, 1.79723659, 2.0562472 , 1.44518935],
       [1.89706256, 1.82423854, 1.654403  , 1.38602543],
       [1.27838519, 2.15619677, 2.22063772, 2.57281806]])

In [32]:
np.sqrt(a)

array([[0.68341693, 0.76566981, 0.84904804, 0.60682811],
       [0.80019164, 0.7753468 , 0.70953521, 0.5713495 ],
       [0.49557816, 0.87655343, 0.89319338, 0.97211204]])

In [33]:
np.log(a)

array([[-0.76130032, -0.53400852, -0.32727902, -0.99901943],
       [-0.44580805, -0.50888973, -0.6862903 , -1.11950836],
       [-1.40406039, -0.26351524, -0.22590434, -0.05656843]])

In [34]:
a.dot(30)

array([[14.01176117, 17.5875078 , 21.62647724, 11.04721048],
       [19.20920006, 18.03487985, 15.10320659,  9.7932074 ],
       [ 7.36793143, 23.05037739, 23.93383246, 28.3500546 ]])

In [35]:
# aggregate functions
a.sum()

6.970521548626188

In [36]:
a.min()

0.24559771431457877

In [37]:
a.max()

0.9450018199857747

In [38]:
a.cumsum()

array([0.46705871, 1.05330897, 1.77419154, 2.14243189, 2.78273856,
       3.38390122, 3.88734144, 4.21378169, 4.4593794 , 5.22772531,
       6.02551973, 6.97052155])

In [39]:
a.mean() # measure of central tendency

0.580876795718849

In [40]:
np.corrcoef(a) # a.mean() is working but a.median() ,a.corrcoef() are not working

array([[ 1.        ,  0.39383044,  0.08393772],
       [ 0.39383044,  1.        , -0.7655001 ],
       [ 0.08393772, -0.7655001 ,  1.        ]])

In [41]:
np.median(a)

0.5937064608352141

In [42]:
np.mean(a)

0.580876795718849

In [43]:
np.std(a) # standard deviation and squre of std is varience

0.19993209986589358

In [44]:
b = a.view() #creating a view copy
b

array([[0.46705871, 0.58625026, 0.72088257, 0.36824035],
       [0.64030667, 0.60116266, 0.50344022, 0.32644025],
       [0.24559771, 0.76834591, 0.79779442, 0.94500182]])

In [45]:
c = a.copy() #create a deep copy

In [46]:
a.sort(axis=0)
a

array([[0.24559771, 0.58625026, 0.50344022, 0.32644025],
       [0.46705871, 0.60116266, 0.72088257, 0.36824035],
       [0.64030667, 0.76834591, 0.79779442, 0.94500182]])

In [47]:
#array manipulation



In [48]:
a.ravel()

array([0.24559771, 0.58625026, 0.50344022, 0.32644025, 0.46705871,
       0.60116266, 0.72088257, 0.36824035, 0.64030667, 0.76834591,
       0.79779442, 0.94500182])

In [49]:
a.reshape(6,2) # we can convert only 3*4 into 4*3 or 6*2 or 2*6 or 12*1 or 1*12 ------->IMPORTANT

array([[0.24559771, 0.58625026],
       [0.50344022, 0.32644025],
       [0.46705871, 0.60116266],
       [0.72088257, 0.36824035],
       [0.64030667, 0.76834591],
       [0.79779442, 0.94500182]])

In [50]:
a[a>0.0000000001] # Boolean indexing --------->IMportant

array([0.24559771, 0.58625026, 0.50344022, 0.32644025, 0.46705871,
       0.60116266, 0.72088257, 0.36824035, 0.64030667, 0.76834591,
       0.79779442, 0.94500182])

In [51]:
a.T

array([[0.24559771, 0.46705871, 0.64030667],
       [0.58625026, 0.60116266, 0.76834591],
       [0.50344022, 0.72088257, 0.79779442],
       [0.32644025, 0.36824035, 0.94500182]])

In [52]:
np.append(a,[3,4])

array([0.24559771, 0.58625026, 0.50344022, 0.32644025, 0.46705871,
       0.60116266, 0.72088257, 0.36824035, 0.64030667, 0.76834591,
       0.79779442, 0.94500182, 3.        , 4.        ])

In [53]:
np.insert(a,4,3) #put 3 on position 4 in array a --->

array([0.24559771, 0.58625026, 0.50344022, 0.32644025, 3.        ,
       0.46705871, 0.60116266, 0.72088257, 0.36824035, 0.64030667,
       0.76834591, 0.79779442, 0.94500182])

In [54]:
np.delete(a,[2]) 

array([0.24559771, 0.58625026, 0.32644025, 0.46705871, 0.60116266,
       0.72088257, 0.36824035, 0.64030667, 0.76834591, 0.79779442,
       0.94500182])

In [55]:
np.concatenate((a,b),axis=1)

array([[0.24559771, 0.58625026, 0.50344022, 0.32644025, 0.24559771,
        0.58625026, 0.50344022, 0.32644025],
       [0.46705871, 0.60116266, 0.72088257, 0.36824035, 0.46705871,
        0.60116266, 0.72088257, 0.36824035],
       [0.64030667, 0.76834591, 0.79779442, 0.94500182, 0.64030667,
        0.76834591, 0.79779442, 0.94500182]])

In [56]:
a

array([[0.24559771, 0.58625026, 0.50344022, 0.32644025],
       [0.46705871, 0.60116266, 0.72088257, 0.36824035],
       [0.64030667, 0.76834591, 0.79779442, 0.94500182]])

In [57]:
a[0][2] == a[0,2] #---> very important to know

True

In [58]:
np.vsplit(a,3) # vertically split into 3 equal rows

[array([[0.24559771, 0.58625026, 0.50344022, 0.32644025]]),
 array([[0.46705871, 0.60116266, 0.72088257, 0.36824035]]),
 array([[0.64030667, 0.76834591, 0.79779442, 0.94500182]])]

In [59]:
np.hsplit(a,4) # horizontally split into 4 columns

[array([[0.24559771],
        [0.46705871],
        [0.64030667]]),
 array([[0.58625026],
        [0.60116266],
        [0.76834591]]),
 array([[0.50344022],
        [0.72088257],
        [0.79779442]]),
 array([[0.32644025],
        [0.36824035],
        [0.94500182]])]

In [60]:
np.vstack(a) # stack vertically 

array([[0.24559771, 0.58625026, 0.50344022, 0.32644025],
       [0.46705871, 0.60116266, 0.72088257, 0.36824035],
       [0.64030667, 0.76834591, 0.79779442, 0.94500182]])

In [61]:
np.hstack(a) # stack horizontally

array([0.24559771, 0.58625026, 0.50344022, 0.32644025, 0.46705871,
       0.60116266, 0.72088257, 0.36824035, 0.64030667, 0.76834591,
       0.79779442, 0.94500182])